/* Sysconfig */
#undef MBEDTLS_HAVE_TIME
#undef MBEDTLS_HAVE_TIME_DATE
#undef MBEDTLS_SELF_TEST
#undef MBEDTLS_FS_IO
//#define MBEDTLS_PLATFORM_MEMORY
//#define MBEDTLS_PLATFORM_NO_STD_FUNCTIONS
#define MBEDTLS_PLATFORM_SNPRINTF_ALT
#define MBEDTLS_PLATFORM_PRINTF_ALT
#define MBEDTLS_DEPRECATED_WARNING
#undef MBEDTLS_ERROR_C
#define MBEDTLS_ERROR_STRERROR_DUMMY
#undef MBEDTLS_TIMING_C
#undef MBEDTLS_NET_C

//check
#define MBEDTLS_AESCE_C

/* Entropy config */
#define MBEDTLS_CTR_DRBG_C
//#def MBEDTLS_ENTROPY_HARDWARE_ALT
#define MBEDTLS_NO_DEFAULT_ENTROPY_SOURCES
#define MBEDTLS_NO_PLATFORM_ENTROPY
#undef MBEDTLS_ENTROPY_MAX_SOURCES

/* Crypto options */
#undef MBEDTLS_PSA_ITS_FILE_C
#undef MBEDTLS_PSA_CRYPTO_STORAGE_C
